//Auto Generate File, Do NOT Modify!!!!!!!!!!!!!!!

module game.net {
	export class ResponseType {
		public static responseList = new burn.util.Map();
		public static COMMONSTATUS:number = 1002;
		public static REPLACEUSER:number = 1005;
		public static MODIFYDATA:number = 1006;
		public static BROADCASTMESSAGE:number = 1007;
		public static GCBROADCASTMESSAGEBACK:number = 1009;
		public static EXCHANGEGOODSBACK:number = 1012;
		public static LOOPEXCHANGERECORDSBACK:number = 1016;
		public static ACTIVECONFIGMESSAGESBACK:number = 1019;
		public static FISHINGGUNBACK:number = 3002;
		public static FISHINGHITBACK:number = 3004;
		public static RANDOMFISHHITBACK:number = 3005;
		public static PONDFISHES:number = 3007;
		public static ADDFISH:number = 3008;
		public static PONDSTATE:number = 3010;
		public static USEITEMBACK:number = 3012;
		public static CHANGEGUNBACK:number = 3014;
		public static USEWARHEADBACK:number = 3016;
		public static LOTTERYCONDITONACCUMULATE:number = 3017;
		public static DRAWLOTTERYBACK:number = 3019;
		public static USELOCKITEM:number = 3020;
		public static LOCKITEMEND:number = 3021;
		public static UPGRADEORFORGEBACK:number = 3023;
		public static LEVELUP:number = 3024;
		public static VIPLEVELUP:number = 3026;
		public static ARENASIGNUPBACK:number = 3028;
		public static GRANDPRIXINFOCHANGE:number = 3029;
		public static THEPEOPLECHANGE:number = 3030;
		public static QUICKGAMEINFOCHANGE:number = 3031;
		public static QUICKGAMERANKRESULT:number = 3033;
		public static QUICKGAMEINTOROOM:number = 3034;
		public static WORLDBOSSINFOBACK:number = 3035;
		public static PIRATERANKRESULT:number = 3037;
		public static SYNCFISHPOSINFO:number = 3039;
		public static SMALLHORNBACK:number = 3042;
		public static LOGINBACK:number = 2002;
		public static REQUESTROOMBACK:number = 2005;
		public static INTOROOMBACK:number = 2007;
		public static QUITROOM:number = 2009;
		public static MAJORPARAMETERCHANGE:number = 2010;
		public static MANUALCHOOSEROOMBACK:number = 2015;
		public static BANKRUPT:number = 2017;
		public static MAIL:number = 2018;
		public static MAILBOX:number = 2020;
		public static FINDUSERBACK:number = 2022;
		public static GIVEITEMBACK:number = 2024;
		public static RECEIVEMAILBACK:number = 2026;
		public static EXCHANGEBACK:number = 2028;
		public static EXCHANGE:number = 2030;
		public static TASKPARAMETERCHANGE:number = 2032;
		public static FINISHTASKBACK:number = 2034;
		public static SHOPBUYBACK:number = 2036;
		public static CHARGEBACK:number = 2038;
		public static MONTHSIGNBACK:number = 2041;
		public static NEXTDAYAWARDBACK:number = 2043;
		public static GETWANBAGIFTBACK:number = 2046;
		public static GETRANKDATABACK:number = 2049;
		public static DAILYLOGINDRAWBACK:number = 2051;
		public static GRANDPRIXRANKBACK:number = 2054;
		public static GRANDPRIXSETTLEMENT:number = 2056;
		public static ROOMONLINEMESSAGE:number = 2059;
		public static LIMITEDTIMEACTIVEINFO:number = 2061;
		public static LIMITEDTIMEACTIVEBACK:number = 2064;
		public static WECHATSHAREINFO:number = 2065;
		public static RECEIVEWECHATSHAREAWARDSEND:number = 2066;
		public static RECEIVEWECHATSHAREAWARDBACK:number = 2067;
		public static init() {
			this.responseList.put(this.COMMONSTATUS, new CommonStatusMessage());
			this.responseList.put(this.REPLACEUSER, new ReplaceUserMessage());
			this.responseList.put(this.MODIFYDATA, new ModifyDataMessage());
			this.responseList.put(this.BROADCASTMESSAGE, new BroadcastMessageMessage());
			this.responseList.put(this.GCBROADCASTMESSAGEBACK, new GCBroadcastMessageBackMessage());
			this.responseList.put(this.EXCHANGEGOODSBACK, new ExchangeGoodsBackMessage());
			this.responseList.put(this.LOOPEXCHANGERECORDSBACK, new LoopExchangeRecordsBackMessage());
			this.responseList.put(this.ACTIVECONFIGMESSAGESBACK, new ActiveConfigMessagesBackMessage());
			this.responseList.put(this.FISHINGGUNBACK, new FishingGunBackMessage());
			this.responseList.put(this.FISHINGHITBACK, new FishingHitBackMessage());
			this.responseList.put(this.RANDOMFISHHITBACK, new RandomFishHitBackMessage());
			this.responseList.put(this.PONDFISHES, new PondFishesMessage());
			this.responseList.put(this.ADDFISH, new AddFishMessage());
			this.responseList.put(this.PONDSTATE, new PondStateMessage());
			this.responseList.put(this.USEITEMBACK, new UseItemBackMessage());
			this.responseList.put(this.CHANGEGUNBACK, new ChangeGunBackMessage());
			this.responseList.put(this.USEWARHEADBACK, UseWarheadBackMessage);
			this.responseList.put(this.LOTTERYCONDITONACCUMULATE, new LotteryConditonAccumulateMessage());
			this.responseList.put(this.DRAWLOTTERYBACK, new DrawLotteryBackMessage());
			this.responseList.put(this.USELOCKITEM, new UseLockItemMessage());
			this.responseList.put(this.LOCKITEMEND, new LockItemEndMessage());
			this.responseList.put(this.UPGRADEORFORGEBACK, UpgradeOrForgeBackMessage);
			this.responseList.put(this.LEVELUP, LevelUpMessage);
			this.responseList.put(this.VIPLEVELUP, VipLevelUpMessage);
			this.responseList.put(this.ARENASIGNUPBACK, ArenaSignUpBackMessage);
			this.responseList.put(this.GRANDPRIXINFOCHANGE, GrandPrixInfoChangeMessage);
			this.responseList.put(this.THEPEOPLECHANGE, ThePeopleChangeMessage);
			this.responseList.put(this.QUICKGAMEINFOCHANGE, QuickGameInfoChangeMessage);
			this.responseList.put(this.QUICKGAMERANKRESULT, QuickGameRankResultMessage);
			this.responseList.put(this.QUICKGAMEINTOROOM, QuickGameIntoRoomMessage);
			this.responseList.put(this.WORLDBOSSINFOBACK, WorldBossInfoBackMessage);
			this.responseList.put(this.PIRATERANKRESULT, PirateRankResultMessage);
			this.responseList.put(this.SYNCFISHPOSINFO, SyncFishPosInfoMessage);
			this.responseList.put(this.SMALLHORNBACK, SmallHornBackMessage);
			this.responseList.put(this.LOGINBACK, LoginBackMessage);
			this.responseList.put(this.REQUESTROOMBACK, RequestRoomBackMessage);
			this.responseList.put(this.INTOROOMBACK, IntoRoomBackMessage);
			this.responseList.put(this.QUITROOM, QuitRoomMessage);
			this.responseList.put(this.MAJORPARAMETERCHANGE, MajorParameterChangeMessage);
			this.responseList.put(this.MANUALCHOOSEROOMBACK, ManualChooseRoomBackMessage);
			this.responseList.put(this.BANKRUPT, BankruptMessage);
			this.responseList.put(this.MAIL, MailMessage);
			this.responseList.put(this.MAILBOX, MailboxMessage);
			this.responseList.put(this.FINDUSERBACK, FindUserBackMessage);
			this.responseList.put(this.GIVEITEMBACK, GiveItemBackMessage);
			this.responseList.put(this.RECEIVEMAILBACK, ReceiveMailBackMessage);
			this.responseList.put(this.EXCHANGEBACK, ExchangeBackMessage);
			this.responseList.put(this.EXCHANGE, ExchangeMessage);
			this.responseList.put(this.TASKPARAMETERCHANGE, new TaskParameterChangeMessage());
			this.responseList.put(this.FINISHTASKBACK, new FinishTaskBackMessage());
			this.responseList.put(this.SHOPBUYBACK, ShopBuyBackMessage);
			this.responseList.put(this.CHARGEBACK, ChargeBackMessage);
			this.responseList.put(this.MONTHSIGNBACK, MonthSignBackMessage);
			this.responseList.put(this.NEXTDAYAWARDBACK, NextDayAwardBackMessage);
			this.responseList.put(this.GETWANBAGIFTBACK, GetWanbaGiftBackMessage);
			this.responseList.put(this.GETRANKDATABACK, GetRankDataBackMessage);
			this.responseList.put(this.DAILYLOGINDRAWBACK, DailyLoginDrawBackMessage);
			this.responseList.put(this.GRANDPRIXRANKBACK, GrandPrixRankBackMessage);
			this.responseList.put(this.GRANDPRIXSETTLEMENT, GrandPrixSettlementMessage);
			this.responseList.put(this.ROOMONLINEMESSAGE, new RoomOnlineMessageMessage());
			this.responseList.put(this.LIMITEDTIMEACTIVEINFO, LimitedTimeActiveInfoMessage);
			this.responseList.put(this.LIMITEDTIMEACTIVEBACK, LimitedTimeActiveBackMessage);
			this.responseList.put(this.WECHATSHAREINFO, WeChatShareInfoMessage);
			this.responseList.put(this.RECEIVEWECHATSHAREAWARDSEND, ReceiveWeChatShareAwardSendMessage);
			this.responseList.put(this.RECEIVEWECHATSHAREAWARDBACK, ReceiveWeChatShareAwardBackMessage);

		}
	}
}
