/**
 * 广播消息枚举类
 */
enum NotifyEnum {
	UPDATE_LOGIN_BTN,	//更新登录按钮状态
	ROOM_UI_INIT_END,	//房间UI初始化完成
	MAIN_UI_INIT,		//主界面初始化
	RES_LOAD_OVER,		//资源加载完成
	GUN_SEND,			//发送开炮事件
	RESET_RATE,			//调整倍率
	HIT_FISH,			//击中鱼
	USE_PROP_ITEM,		//使用道具
	USE_WARHEAD,		//使用弹头道具
	OPEN_LOTTERY_UI,	//打开抽奖界面
	LOCKED_FISH_DISAPPEAR,	//锁定的鱼消不存在了
	UPDATE_ROOM_UI_COINS,	//更新房间内玩家金币显示
	UPDATE_ROOM_UI_BULLETS, //更新房间内玩家子弹显示
	UPDATE_ROOM_UI_MONEY,	//更新房间内玩家钻石及道具显示
	SEND_CLICK_FISH,	//发送点击到的鱼的uid
	CLICK_MAIN_BTN,		//点击主界面上面的功能按钮
	CLICK_MAIN_FUN_ITEM,//点击两边非中间item的时候
	CLICK_EXIT_ROOM,		//点击退出房间按钮
	OPEN_SELECT_ROOM,    //点击选房间按钮
	ROOMLIST_RESOUCE_LOADED,  //选房界面的资源完成加载
	OPEN_MAINVIEW_LOADING_AND_INTO_ROOM, //打开mainview的loading界面
	LOCKED_FISH_CHANGE,   //更改锁定的鱼
	LOTTERY_UI_LOAD_END,		//抽奖界面加载完成
	SET_PROP_NUM,		//设置道具数量
	CLICK_BAG_ITEM,		//点击背包中的道具
	CHECK_UNLOCKGUNUI_LOADED, //检测解锁炮倍的UI加载完成
	SET_USEENSENCE_FLAG,     //设置知否使用水晶精华进行锻造
	TRIGGER_CONFIRM_OK,    //触发 confirm界面的OK
	CHECK_FORGEUI_LOADED,   //检测锻造界面是否加载完成
	BANKRUPT_MESSAGE,	//救济金通用消息
	SHOW_EMAIL_LIST,          //显示邮件列表
	SEND_ITEM_TO_USER,          //给玩家赠送
	USE_ITEM_BY_BAG,            //在背包里。点击使用按钮的消息
	RECEIVE_MAIL_SEND,        //查看领取邮件
	GIVE_ITEM_DATA,           //给玩家赠送。同步数据消息
	REFRESH_EMAIL,             //刷新邮件
	SET_EXCHANGE_LIST,          //设置兑换界面
	EXCHANGE_ITEM,               //兑换物品
	CHECK_GUN_RESET,              //查找最新的炮倍
	USER_INFO_UI_LOADED,            //角色加载成功
	EXCHANGE_SURE_LOADED,           //兑换确认加载成功
	EXCHANGE_RECODE_LOADED,          //兑换记录加载陈宫
	SHOW_CHAKAN_PANEL,                  //显示查看板子
	AUTO_GUN_FIRE,				//自动开炮
	TASK_UI_LOADED,                 //任务UI加载
	UPDATE_MAIN_DATA,			//刷新主界面数据
	TASK_CHANGE_LIST,                //任务切换列表
	GUIDE_OPEN,                  //引导开始
	GUIDE_CLOSE,                  //引导结束
	TASK_GUIDE_PANEL_LOADED,       //任务引导板子加载结束
	TASK_GUIDE_CHANGE,              //新手任务更改状态
	TASK_GUIDE_LOAD,                 //加载任务板子
	CHECK_MAIN_ALERT,                //检查主界面红点
	SHOP_BUY_ITEM,				//商城界面购买物品
	CHANGE_SETTING,              //设置更改
	SHOW_CHARGE_LIST,              //显示充值界面
	CHANGE_GUN_UI_LOADED,             //更换炮倍UI加载完成
	BUY_CHARGE_ITEM,			//充值界面购买物品
	TASK_ACT_CHANGE,              //活跃度任务更新
	OPEN_NOTICE_UI,				//打开公告UI
	CLICK_NOTICE_ITEM,			//点击公告item
	REQ_QQZONE_GIFT,			//请求QQ玩吧礼包
	CLOSE_QQZONE_GIFT,			//关闭QQ玩吧礼包
	SIGN_UI_LOADED,              //签到UI加载完成
	CHECK_POP,                  //检查弹出板子
	POP_EXCHANGE,               //弹出兑换板子
	POP_UPDATEEXCHANGE,				//更新兑换板数值
	SET_RANK_LIST,               //显示排行榜
	DJS_ITEM_LOADED,              //大奖赛UIloaded
	SIGN_UP_DJS,               //大奖赛报名
	DJS_TASK_CHANGE,            //大奖赛任务变更
	DJS_RESULT_SEND,             //大奖赛结束
	CLOSE_SIGN_VIEW,               //关闭报名界面
	POP_CHARGE,                     //弹出充值界面
	CHANGE_WAIT_PEOPLE,             //更改等待人数信息
	POP_CIRI,                      //弹出次日礼包
	CLOSE_CIRI,                     //关闭次日礼包
	CHANGE_PHOENIX_UI,              //凤凰UI变更
	CHANGE_ACTIVE,                   //切换活动
	PRICE_TASK_CHANGE,              //悬赏任务
	CLEAR_PRICE_TASK,                //清除悬赏任务
	SHOW_PRICE_RANK,                //显示排行信息
	REFRES_ROOM_ONLINE,              //刷新房间在线人数
	CHECN_VIP_ITEM,               //检查vip对道具的影响
	UPDATE_GORGEOUS_STATE,			//更新华丽版和流畅版状态
	ACTIVE_CONFIG_DATA_LOAEDED,     //活动信息
	PRICE_CHALLENGE_FAIL,            //海盗挑战失败
	SEND_TRUMPET_MSG,				//发送小喇叭消息
	SHARE_GAIN_UI_LOADED            //分享奖励UI加载完毕
} 