//Auto Generate File, Do NOT Modify!!!!!!!!!!!!!!!
var __reflect = (this && this.__reflect) || function (p, c, t) {
    p.__class__ = c, t ? t.push(c) : t = [c], p.__types__ = p.__types__ ? t.concat(p.__types__) : t;
};
var game;
(function (game) {
    var net;
    (function (net) {
        var ResponseType = (function () {
            function ResponseType() {
            }
            ResponseType.init = function () {
                this.responseList.put(this.COMMONSTATUS, new CommonStatusMessage());
                this.responseList.put(this.REPLACEUSER, new ReplaceUserMessage());
                this.responseList.put(this.MODIFYDATA, new ModifyDataMessage());
                this.responseList.put(this.BROADCASTMESSAGE, new BroadcastMessageMessage());
                this.responseList.put(this.GCBROADCASTMESSAGEBACK, new GCBroadcastMessageBackMessage());
                this.responseList.put(this.EXCHANGEGOODSBACK, new ExchangeGoodsBackMessage());
                this.responseList.put(this.LOOPEXCHANGERECORDSBACK, new LoopExchangeRecordsBackMessage());
                this.responseList.put(this.ACTIVECONFIGMESSAGESBACK, new ActiveConfigMessagesBackMessage());
                this.responseList.put(this.FISHINGGUNBACK, new FishingGunBackMessage());
                this.responseList.put(this.FISHINGHITBACK, new FishingHitBackMessage());
                this.responseList.put(this.RANDOMFISHHITBACK, new RandomFishHitBackMessage());
                this.responseList.put(this.PONDFISHES, new PondFishesMessage());
                this.responseList.put(this.ADDFISH, new AddFishMessage());
                this.responseList.put(this.PONDSTATE, new PondStateMessage());
                this.responseList.put(this.USEITEMBACK, new UseItemBackMessage());
                this.responseList.put(this.CHANGEGUNBACK, new ChangeGunBackMessage());
                this.responseList.put(this.USEWARHEADBACK, UseWarheadBackMessage);
                this.responseList.put(this.LOTTERYCONDITONACCUMULATE, new LotteryConditonAccumulateMessage());
                this.responseList.put(this.DRAWLOTTERYBACK, new DrawLotteryBackMessage());
                this.responseList.put(this.USELOCKITEM, new UseLockItemMessage());
                this.responseList.put(this.LOCKITEMEND, new LockItemEndMessage());
                this.responseList.put(this.UPGRADEORFORGEBACK, UpgradeOrForgeBackMessage);
                this.responseList.put(this.LEVELUP, LevelUpMessage);
                this.responseList.put(this.VIPLEVELUP, VipLevelUpMessage);
                this.responseList.put(this.ARENASIGNUPBACK, ArenaSignUpBackMessage);
                this.responseList.put(this.GRANDPRIXINFOCHANGE, GrandPrixInfoChangeMessage);
                this.responseList.put(this.THEPEOPLECHANGE, ThePeopleChangeMessage);
                this.responseList.put(this.QUICKGAMEINFOCHANGE, QuickGameInfoChangeMessage);
                this.responseList.put(this.QUICKGAMERANKRESULT, QuickGameRankResultMessage);
                this.responseList.put(this.QUICKGAMEINTOROOM, QuickGameIntoRoomMessage);
                this.responseList.put(this.WORLDBOSSINFOBACK, WorldBossInfoBackMessage);
                this.responseList.put(this.PIRATERANKRESULT, PirateRankResultMessage);
                this.responseList.put(this.SYNCFISHPOSINFO, SyncFishPosInfoMessage);
                this.responseList.put(this.SMALLHORNBACK, SmallHornBackMessage);
                this.responseList.put(this.LOGINBACK, LoginBackMessage);
                this.responseList.put(this.REQUESTROOMBACK, RequestRoomBackMessage);
                this.responseList.put(this.INTOROOMBACK, IntoRoomBackMessage);
                this.responseList.put(this.QUITROOM, QuitRoomMessage);
                this.responseList.put(this.MAJORPARAMETERCHANGE, MajorParameterChangeMessage);
                this.responseList.put(this.MANUALCHOOSEROOMBACK, ManualChooseRoomBackMessage);
                this.responseList.put(this.BANKRUPT, BankruptMessage);
                this.responseList.put(this.MAIL, MailMessage);
                this.responseList.put(this.MAILBOX, MailboxMessage);
                this.responseList.put(this.FINDUSERBACK, FindUserBackMessage);
                this.responseList.put(this.GIVEITEMBACK, GiveItemBackMessage);
                this.responseList.put(this.RECEIVEMAILBACK, ReceiveMailBackMessage);
                this.responseList.put(this.EXCHANGEBACK, ExchangeBackMessage);
                this.responseList.put(this.EXCHANGE, ExchangeMessage);
                this.responseList.put(this.TASKPARAMETERCHANGE, new TaskParameterChangeMessage());
                this.responseList.put(this.FINISHTASKBACK, new FinishTaskBackMessage());
                this.responseList.put(this.SHOPBUYBACK, ShopBuyBackMessage);
                this.responseList.put(this.CHARGEBACK, ChargeBackMessage);
                this.responseList.put(this.MONTHSIGNBACK, MonthSignBackMessage);
                this.responseList.put(this.NEXTDAYAWARDBACK, NextDayAwardBackMessage);
                this.responseList.put(this.GETWANBAGIFTBACK, GetWanbaGiftBackMessage);
                this.responseList.put(this.GETRANKDATABACK, GetRankDataBackMessage);
                this.responseList.put(this.DAILYLOGINDRAWBACK, DailyLoginDrawBackMessage);
                this.responseList.put(this.GRANDPRIXRANKBACK, GrandPrixRankBackMessage);
                this.responseList.put(this.GRANDPRIXSETTLEMENT, GrandPrixSettlementMessage);
                this.responseList.put(this.ROOMONLINEMESSAGE, new RoomOnlineMessageMessage());
                this.responseList.put(this.LIMITEDTIMEACTIVEINFO, LimitedTimeActiveInfoMessage);
                this.responseList.put(this.LIMITEDTIMEACTIVEBACK, LimitedTimeActiveBackMessage);
                this.responseList.put(this.WECHATSHAREINFO, WeChatShareInfoMessage);
                this.responseList.put(this.RECEIVEWECHATSHAREAWARDSEND, ReceiveWeChatShareAwardSendMessage);
                this.responseList.put(this.RECEIVEWECHATSHAREAWARDBACK, ReceiveWeChatShareAwardBackMessage);
            };
            return ResponseType;
        }());
        ResponseType.responseList = new burn.util.Map();
        ResponseType.COMMONSTATUS = 1002;
        ResponseType.REPLACEUSER = 1005;
        ResponseType.MODIFYDATA = 1006;
        ResponseType.BROADCASTMESSAGE = 1007;
        ResponseType.GCBROADCASTMESSAGEBACK = 1009;
        ResponseType.EXCHANGEGOODSBACK = 1012;
        ResponseType.LOOPEXCHANGERECORDSBACK = 1016;
        ResponseType.ACTIVECONFIGMESSAGESBACK = 1019;
        ResponseType.FISHINGGUNBACK = 3002;
        ResponseType.FISHINGHITBACK = 3004;
        ResponseType.RANDOMFISHHITBACK = 3005;
        ResponseType.PONDFISHES = 3007;
        ResponseType.ADDFISH = 3008;
        ResponseType.PONDSTATE = 3010;
        ResponseType.USEITEMBACK = 3012;
        ResponseType.CHANGEGUNBACK = 3014;
        ResponseType.USEWARHEADBACK = 3016;
        ResponseType.LOTTERYCONDITONACCUMULATE = 3017;
        ResponseType.DRAWLOTTERYBACK = 3019;
        ResponseType.USELOCKITEM = 3020;
        ResponseType.LOCKITEMEND = 3021;
        ResponseType.UPGRADEORFORGEBACK = 3023;
        ResponseType.LEVELUP = 3024;
        ResponseType.VIPLEVELUP = 3026;
        ResponseType.ARENASIGNUPBACK = 3028;
        ResponseType.GRANDPRIXINFOCHANGE = 3029;
        ResponseType.THEPEOPLECHANGE = 3030;
        ResponseType.QUICKGAMEINFOCHANGE = 3031;
        ResponseType.QUICKGAMERANKRESULT = 3033;
        ResponseType.QUICKGAMEINTOROOM = 3034;
        ResponseType.WORLDBOSSINFOBACK = 3035;
        ResponseType.PIRATERANKRESULT = 3037;
        ResponseType.SYNCFISHPOSINFO = 3039;
        ResponseType.SMALLHORNBACK = 3042;
        ResponseType.LOGINBACK = 2002;
        ResponseType.REQUESTROOMBACK = 2005;
        ResponseType.INTOROOMBACK = 2007;
        ResponseType.QUITROOM = 2009;
        ResponseType.MAJORPARAMETERCHANGE = 2010;
        ResponseType.MANUALCHOOSEROOMBACK = 2015;
        ResponseType.BANKRUPT = 2017;
        ResponseType.MAIL = 2018;
        ResponseType.MAILBOX = 2020;
        ResponseType.FINDUSERBACK = 2022;
        ResponseType.GIVEITEMBACK = 2024;
        ResponseType.RECEIVEMAILBACK = 2026;
        ResponseType.EXCHANGEBACK = 2028;
        ResponseType.EXCHANGE = 2030;
        ResponseType.TASKPARAMETERCHANGE = 2032;
        ResponseType.FINISHTASKBACK = 2034;
        ResponseType.SHOPBUYBACK = 2036;
        ResponseType.CHARGEBACK = 2038;
        ResponseType.MONTHSIGNBACK = 2041;
        ResponseType.NEXTDAYAWARDBACK = 2043;
        ResponseType.GETWANBAGIFTBACK = 2046;
        ResponseType.GETRANKDATABACK = 2049;
        ResponseType.DAILYLOGINDRAWBACK = 2051;
        ResponseType.GRANDPRIXRANKBACK = 2054;
        ResponseType.GRANDPRIXSETTLEMENT = 2056;
        ResponseType.ROOMONLINEMESSAGE = 2059;
        ResponseType.LIMITEDTIMEACTIVEINFO = 2061;
        ResponseType.LIMITEDTIMEACTIVEBACK = 2064;
        ResponseType.WECHATSHAREINFO = 2065;
        ResponseType.RECEIVEWECHATSHAREAWARDSEND = 2066;
        ResponseType.RECEIVEWECHATSHAREAWARDBACK = 2067;
        net.ResponseType = ResponseType;
        __reflect(ResponseType.prototype, "game.net.ResponseType");
    })(net = game.net || (game.net = {}));
})(game || (game = {}));
//# sourceMappingURL=ResponseType.js.map